// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4ASoQMdeFRySF8Jh7ZlMyfjenowWKTM',
    appId: '1:729492022568:web:e9fec4fde055cca68c9c1d',
    messagingSenderId: '729492022568',
    projectId: 'poseidon-aquaculture',
    authDomain: 'poseidon-aquaculture.firebaseapp.com',
    storageBucket: 'poseidon-aquaculture.firebasestorage.app',
    measurementId: 'G-6D9MW6C1ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFD11OWqkUpWRm2s6yX9OaJ-EWg69fC0',
    appId: '1:729492022568:android:b510a10f69e739678c9c1d',
    messagingSenderId: '729492022568',
    projectId: 'poseidon-aquaculture',
    storageBucket: 'poseidon-aquaculture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dAEJa8nz0webF3RcAJsfPKKw-ImEpU8',
    appId: '1:729492022568:ios:f0c6e362e1af62218c9c1d',
    messagingSenderId: '729492022568',
    projectId: 'poseidon-aquaculture',
    storageBucket: 'poseidon-aquaculture.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

}